// Generated by delombok at Sun Apr 18 22:20:18 CEST 2021
/*
 * Copyright (c) 2016-present, Takayuki Maruyama
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ar4k.agent.mattermost.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AuthData {
	@JsonProperty("client_id")
	private String clientId;
	@JsonProperty("user_id")
	private String userId;
	@JsonProperty("code")
	private String code;
	@JsonProperty("expires_in")
	private long expiresIn;
	@JsonProperty("create_at")
	private long createAt;
	@JsonProperty("redirect_url")
	private String redirectUrl;
	@JsonProperty("state")
	private String state;
	@JsonProperty("scope")
	private String scope;

	@java.lang.SuppressWarnings("all")
	public AuthData() {
	}

	@java.lang.SuppressWarnings("all")
	public String getClientId() {
		return this.clientId;
	}

	@java.lang.SuppressWarnings("all")
	public String getUserId() {
		return this.userId;
	}

	@java.lang.SuppressWarnings("all")
	public String getCode() {
		return this.code;
	}

	@java.lang.SuppressWarnings("all")
	public long getExpiresIn() {
		return this.expiresIn;
	}

	@java.lang.SuppressWarnings("all")
	public long getCreateAt() {
		return this.createAt;
	}

	@java.lang.SuppressWarnings("all")
	public String getRedirectUrl() {
		return this.redirectUrl;
	}

	@java.lang.SuppressWarnings("all")
	public String getState() {
		return this.state;
	}

	@java.lang.SuppressWarnings("all")
	public String getScope() {
		return this.scope;
	}

	@JsonProperty("client_id")
	@java.lang.SuppressWarnings("all")
	public void setClientId(final String clientId) {
		this.clientId = clientId;
	}

	@JsonProperty("user_id")
	@java.lang.SuppressWarnings("all")
	public void setUserId(final String userId) {
		this.userId = userId;
	}

	@JsonProperty("code")
	@java.lang.SuppressWarnings("all")
	public void setCode(final String code) {
		this.code = code;
	}

	@JsonProperty("expires_in")
	@java.lang.SuppressWarnings("all")
	public void setExpiresIn(final long expiresIn) {
		this.expiresIn = expiresIn;
	}

	@JsonProperty("create_at")
	@java.lang.SuppressWarnings("all")
	public void setCreateAt(final long createAt) {
		this.createAt = createAt;
	}

	@JsonProperty("redirect_url")
	@java.lang.SuppressWarnings("all")
	public void setRedirectUrl(final String redirectUrl) {
		this.redirectUrl = redirectUrl;
	}

	@JsonProperty("state")
	@java.lang.SuppressWarnings("all")
	public void setState(final String state) {
		this.state = state;
	}

	@JsonProperty("scope")
	@java.lang.SuppressWarnings("all")
	public void setScope(final String scope) {
		this.scope = scope;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this)
			return true;
		if (!(o instanceof AuthData))
			return false;
		final AuthData other = (AuthData) o;
		if (!other.canEqual((java.lang.Object) this))
			return false;
		if (this.getExpiresIn() != other.getExpiresIn())
			return false;
		if (this.getCreateAt() != other.getCreateAt())
			return false;
		final java.lang.Object this$clientId = this.getClientId();
		final java.lang.Object other$clientId = other.getClientId();
		if (this$clientId == null ? other$clientId != null : !this$clientId.equals(other$clientId))
			return false;
		final java.lang.Object this$userId = this.getUserId();
		final java.lang.Object other$userId = other.getUserId();
		if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId))
			return false;
		final java.lang.Object this$code = this.getCode();
		final java.lang.Object other$code = other.getCode();
		if (this$code == null ? other$code != null : !this$code.equals(other$code))
			return false;
		final java.lang.Object this$redirectUrl = this.getRedirectUrl();
		final java.lang.Object other$redirectUrl = other.getRedirectUrl();
		if (this$redirectUrl == null ? other$redirectUrl != null : !this$redirectUrl.equals(other$redirectUrl))
			return false;
		final java.lang.Object this$state = this.getState();
		final java.lang.Object other$state = other.getState();
		if (this$state == null ? other$state != null : !this$state.equals(other$state))
			return false;
		final java.lang.Object this$scope = this.getScope();
		final java.lang.Object other$scope = other.getScope();
		if (this$scope == null ? other$scope != null : !this$scope.equals(other$scope))
			return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AuthData;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final long $expiresIn = this.getExpiresIn();
		result = result * PRIME + (int) ($expiresIn >>> 32 ^ $expiresIn);
		final long $createAt = this.getCreateAt();
		result = result * PRIME + (int) ($createAt >>> 32 ^ $createAt);
		final java.lang.Object $clientId = this.getClientId();
		result = result * PRIME + ($clientId == null ? 43 : $clientId.hashCode());
		final java.lang.Object $userId = this.getUserId();
		result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
		final java.lang.Object $code = this.getCode();
		result = result * PRIME + ($code == null ? 43 : $code.hashCode());
		final java.lang.Object $redirectUrl = this.getRedirectUrl();
		result = result * PRIME + ($redirectUrl == null ? 43 : $redirectUrl.hashCode());
		final java.lang.Object $state = this.getState();
		result = result * PRIME + ($state == null ? 43 : $state.hashCode());
		final java.lang.Object $scope = this.getScope();
		result = result * PRIME + ($scope == null ? 43 : $scope.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "AuthData(clientId=" + this.getClientId() + ", userId=" + this.getUserId() + ", code=" + this.getCode()
				+ ", expiresIn=" + this.getExpiresIn() + ", createAt=" + this.getCreateAt() + ", redirectUrl="
				+ this.getRedirectUrl() + ", state=" + this.getState() + ", scope=" + this.getScope() + ")";
	}
}
