// Generated by delombok at Sun Apr 18 22:20:18 CEST 2021
/*
 * Copyright (c) 2016-present, Takayuki Maruyama
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ar4k.agent.mattermost.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Security bulletin.
 * 
 * @author Takayuki Maruyama
 */
public class SecurityBulletin {
  @JsonProperty("id")
  private String id;
  @JsonProperty("applies_to_version")
  private String appliesToVersion;

  @java.lang.SuppressWarnings("all")
  public SecurityBulletin() {
  }

  @java.lang.SuppressWarnings("all")
  public String getId() {
    return this.id;
  }

  @java.lang.SuppressWarnings("all")
  public String getAppliesToVersion() {
    return this.appliesToVersion;
  }

  @JsonProperty("id")
  @java.lang.SuppressWarnings("all")
  public void setId(final String id) {
    this.id = id;
  }

  @JsonProperty("applies_to_version")
  @java.lang.SuppressWarnings("all")
  public void setAppliesToVersion(final String appliesToVersion) {
    this.appliesToVersion = appliesToVersion;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof SecurityBulletin)) return false;
    final SecurityBulletin other = (SecurityBulletin) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$id = this.getId();
    final java.lang.Object other$id = other.getId();
    if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
    final java.lang.Object this$appliesToVersion = this.getAppliesToVersion();
    final java.lang.Object other$appliesToVersion = other.getAppliesToVersion();
    if (this$appliesToVersion == null ? other$appliesToVersion != null : !this$appliesToVersion.equals(other$appliesToVersion)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof SecurityBulletin;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $id = this.getId();
    result = result * PRIME + ($id == null ? 43 : $id.hashCode());
    final java.lang.Object $appliesToVersion = this.getAppliesToVersion();
    result = result * PRIME + ($appliesToVersion == null ? 43 : $appliesToVersion.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "SecurityBulletin(id=" + this.getId() + ", appliesToVersion=" + this.getAppliesToVersion() + ")";
  }
}
