// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface AgentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.Agent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agentUniqueName = 1;</code>
   */
  java.lang.String getAgentUniqueName();
  /**
   * <code>string agentUniqueName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAgentUniqueNameBytes();

  /**
   * <code>string shortDescription = 2;</code>
   */
  java.lang.String getShortDescription();
  /**
   * <code>string shortDescription = 2;</code>
   */
  com.google.protobuf.ByteString
      getShortDescriptionBytes();

  /**
   * <code>.beacon.RegisterReply registerData = 3;</code>
   */
  boolean hasRegisterData();
  /**
   * <code>.beacon.RegisterReply registerData = 3;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.RegisterReply getRegisterData();
  /**
   * <code>.beacon.RegisterReply registerData = 3;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.RegisterReplyOrBuilder getRegisterDataOrBuilder();

  /**
   * <code>string jsonHardwareInfo = 4;</code>
   */
  java.lang.String getJsonHardwareInfo();
  /**
   * <code>string jsonHardwareInfo = 4;</code>
   */
  com.google.protobuf.ByteString
      getJsonHardwareInfoBytes();

  /**
   * <code>.beacon.Timestamp lastContact = 5;</code>
   */
  boolean hasLastContact();
  /**
   * <code>.beacon.Timestamp lastContact = 5;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.Timestamp getLastContact();
  /**
   * <code>.beacon.Timestamp lastContact = 5;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.TimestampOrBuilder getLastContactOrBuilder();
}
