// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface AgentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.Agent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string hardwareInfoAsJson = 2;
   * string registerCode = 2; // ritornato in registrazione
   *int32 pollingFrequency = 3;
   *int64 timestampRegistration = 3;
   * </pre>
   *
   * <code>string agentUniqueName = 1;</code>
   */
  java.lang.String getAgentUniqueName();
  /**
   * <pre>
   *string hardwareInfoAsJson = 2;
   * string registerCode = 2; // ritornato in registrazione
   *int32 pollingFrequency = 3;
   *int64 timestampRegistration = 3;
   * </pre>
   *
   * <code>string agentUniqueName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAgentUniqueNameBytes();
}
