// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface ApproveAgentRequestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.ApproveAgentRequestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idRequest = 1;</code>
   */
  java.lang.String getIdRequest();
  /**
   * <code>string idRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdRequestBytes();

  /**
   * <pre>
   * da utilizzare se il certificato viene firmato esternamente
   * </pre>
   *
   * <code>string cert = 2;</code>
   */
  java.lang.String getCert();
  /**
   * <pre>
   * da utilizzare se il certificato viene firmato esternamente
   * </pre>
   *
   * <code>string cert = 2;</code>
   */
  com.google.protobuf.ByteString
      getCertBytes();

  /**
   * <code>string note = 3;</code>
   */
  java.lang.String getNote();
  /**
   * <code>string note = 3;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();
}
