// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public final class BeaconMirrorService {
  private BeaconMirrorService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Timestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Timestamp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RegisterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RegisterReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Agent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Agent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ConfigReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ConfigReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_FlowMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_FlowMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestToAgent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestToAgent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CommandReplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CommandReplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_HealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_HealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_LogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_LogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ExceptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ExceptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_StreamData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_StreamData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ListAgentsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ListAgentsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ListSslAuthoritiesReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ListSslAuthoritiesReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_SslAuthority_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_SslAuthority_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ElaborateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ElaborateMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ElaborateMessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ElaborateMessageReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ListCommandsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ListCommandsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ListCommandsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ListCommandsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CompleteCommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CompleteCommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CompleteCommandReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CompleteCommandReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CreateProxySocksOnAgentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CreateProxySocksOnAgentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CreateProxySocksOnAgentRequest_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CreateProxySocksOnAgentRequest_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_TunnelCreatedReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_TunnelCreatedReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ExposeAgentPortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ExposeAgentPortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ExposeAgentPortRequest_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ExposeAgentPortRequest_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Tunnel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Tunnel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Tunnel_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Tunnel_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_ListTunnelsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_ListTunnelsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_CloseTunnelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_CloseTunnelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_MessageEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_MessageEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_MessageEventRequest_EventDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_MessageEventRequest_EventDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_FlowMessagePot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_FlowMessagePot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestToAgentPot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestToAgentPot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestToAgentPot_RequestDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestToAgentPot_RequestDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestSubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestSubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestPolling_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestPolling_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_FlowMessageData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_FlowMessageData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_FlowMessageDataJson_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_FlowMessageDataJson_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_DataJson_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_DataJson_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestWrite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestWrite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beacon_RequestWriteText_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beacon_RequestWriteText_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ar4k_beacon.proto\022\006beacon\"|\n\017RegisterR" +
      "equest\022\014\n\004name\030\001 \001(\t\022\022\n\nrequestCsr\030\002 \001(\t" +
      "\022\022\n\ndisplayKey\030\003 \001(\t\022\037\n\004time\030\004 \001(\0132\021.bea" +
      "con.Timestamp\022\022\n\njsonHealth\030\005 \001(\t\"+\n\tTim" +
      "estamp\022\017\n\007seconds\030\001 \001(\003\022\r\n\005nanos\030\002 \001(\005\"\210" +
      "\001\n\rRegisterReply\022\024\n\014registerCode\030\001 \001(\t\022\033" +
      "\n\023monitoringFrequency\030\002 \001(\005\022\014\n\004cert\030\003 \001(" +
      "\t\022\n\n\002ca\030\004 \001(\t\022*\n\022statusRegistration\030\005 \001(" +
      "\0132\016.beacon.Status\"-\n\006Status\022#\n\006status\030\001 " +
      "\001(\0162\023.beacon.StatusValue\"l\n\005Agent\022\027\n\017age" +
      "ntUniqueName\030\001 \001(\t\022\021\n\tsecretKey\030\002 \001(\t\022\030\n" +
      "\020pollingFrequency\030\003 \001(\005\022\035\n\025timestampRegi" +
      "stration\030\004 \001(\003\"\035\n\013ConfigReply\022\016\n\006config\030" +
      "\001 \001(\t\"7\n\013FlowMessage\022(\n\010toDoList\030\001 \003(\0132\026" +
      ".beacon.RequestToAgent\"\267\001\n\016RequestToAgen" +
      "t\022!\n\004type\030\001 \001(\0162\023.beacon.CommandType\022\035\n\006" +
      "caller\030\002 \001(\0132\r.beacon.Agent\022\027\n\017uniqueIdR" +
      "equest\030\003 \001(\t\022\026\n\016requestCommand\030\004 \001(\t\022\r\n\005" +
      "words\030\005 \003(\t\022\021\n\twordIndex\030\006 \001(\005\022\020\n\010positi" +
      "on\030\007 \001(\005\"n\n\013ChatMessage\022\"\n\013agentSender\030\001" +
      " \001(\0132\r.beacon.Agent\022\'\n\020agentDestination\030" +
      "\002 \001(\0132\r.beacon.Agent\022\022\n\nmessageTxt\030\003 \001(\t" +
      "\"\234\001\n\023CommandReplyRequest\022\027\n\017uniqueIdRequ" +
      "est\030\001 \001(\t\022\"\n\013agentSender\030\002 \001(\0132\r.beacon." +
      "Agent\022\'\n\020agentDestination\030\003 \001(\0132\r.beacon" +
      ".Agent\022\017\n\007replies\030\004 \003(\t\022\016\n\006errors\030\005 \003(\t\"" +
      "I\n\rHealthRequest\022\"\n\013agentSender\030\001 \001(\0132\r." +
      "beacon.Agent\022\024\n\014hardwareInfo\030\002 \001(\t\"h\n\nLo" +
      "gRequest\022\"\n\013agentSender\030\001 \001(\0132\r.beacon.A" +
      "gent\022%\n\010severity\030\002 \001(\0162\023.beacon.LogSever" +
      "ity\022\017\n\007logLine\030\003 \001(\t\"m\n\020ExceptionRequest" +
      "\022\"\n\013agentSender\030\001 \001(\0132\r.beacon.Agent\022\030\n\020" +
      "messageException\030\002 \001(\t\022\033\n\023stackTraceExce" +
      "ption\030\003 \001(\t\"\\\n\nStreamData\022 \n\tfromAgent\030\001" +
      " \001(\0132\r.beacon.Agent\022\036\n\007toAgent\030\002 \001(\0132\r.b" +
      "eacon.Agent\022\014\n\004data\030\003 \001(\014\"\007\n\005Empty\"P\n\017Li" +
      "stAgentsReply\022\036\n\006result\030\001 \001(\0132\016.beacon.S" +
      "tatus\022\035\n\006agents\030\002 \003(\0132\r.beacon.Agent\"d\n\027" +
      "ListSslAuthoritiesReply\022\036\n\006result\030\001 \001(\0132" +
      "\016.beacon.Status\022)\n\013authorities\030\002 \003(\0132\024.b" +
      "eacon.SslAuthority\"G\n\014SslAuthority\022\r\n\005la" +
      "bel\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\023\n\013author" +
      "ityCa\030\003 \001(\t\"y\n\027ElaborateMessageRequest\022\"" +
      "\n\013agentTarget\030\001 \001(\0132\r.beacon.Agent\022\"\n\013ag" +
      "entSender\030\002 \001(\0132\r.beacon.Agent\022\026\n\016comman" +
      "dMessage\030\003 \001(\t\"6\n\025ElaborateMessageReply\022" +
      "\r\n\005reply\030\001 \001(\t\022\016\n\006errors\030\002 \003(\t\"]\n\023ListCo" +
      "mmandsRequest\022\"\n\013agentTarget\030\001 \001(\0132\r.bea" +
      "con.Agent\022\"\n\013agentSender\030\002 \001(\0132\r.beacon." +
      "Agent\"6\n\021ListCommandsReply\022!\n\010commands\030\001" +
      " \003(\0132\017.beacon.Command\">\n\007Command\022\"\n\013agen" +
      "tSender\030\001 \001(\0132\r.beacon.Agent\022\017\n\007command\030" +
      "\002 \001(\t\"\224\001\n\026CompleteCommandRequest\022\"\n\013agen" +
      "tTarget\030\001 \001(\0132\r.beacon.Agent\022\"\n\013agentSen" +
      "der\030\002 \001(\0132\r.beacon.Agent\022\r\n\005words\030\003 \003(\t\022" +
      "\021\n\twordIndex\030\004 \001(\005\022\020\n\010position\030\005 \001(\005\"7\n\024" +
      "CompleteCommandReply\022\017\n\007replies\030\001 \003(\t\022\016\n" +
      "\006errors\030\002 \003(\t\"\347\001\n\036CreateProxySocksOnAgen" +
      "tRequest\022\"\n\013agentTarget\030\001 \001(\0132\r.beacon.A" +
      "gent\022\"\n\013agentSender\030\002 \001(\0132\r.beacon.Agent" +
      "\022J\n\nparameters\030\003 \003(\01326.beacon.CreateProx" +
      "ySocksOnAgentRequest.ParametersEntry\0321\n\017" +
      "ParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"l\n\022TunnelCreatedReply\022\026\n\016uniqueT" +
      "unnelId\030\001 \001(\t\022\036\n\006status\030\002 \001(\0132\016.beacon.S" +
      "tatus\022\036\n\006tunnel\030\003 \001(\0132\016.beacon.Tunnel\"\327\001" +
      "\n\026ExposeAgentPortRequest\022\"\n\013agentTarget\030" +
      "\001 \001(\0132\r.beacon.Agent\022\"\n\013agentSender\030\002 \001(" +
      "\0132\r.beacon.Agent\022B\n\nparameters\030\003 \003(\0132..b" +
      "eacon.ExposeAgentPortRequest.ParametersE" +
      "ntry\0321\n\017ParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\"\353\001\n\006Tunnel\022\026\n\016uniqueTunn" +
      "elId\030\001 \001(\t\022 \n\tagentFrom\030\002 \001(\0132\r.beacon.A" +
      "gent\022\036\n\007agentTo\030\003 \001(\0132\r.beacon.Agent\022 \n\004" +
      "type\030\004 \001(\0162\022.beacon.TunnelType\0222\n\nparame" +
      "ters\030\005 \003(\0132\036.beacon.Tunnel.ParametersEnt" +
      "ry\0321\n\017ParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"3\n\020ListTunnelsReply\022\037\n\007tun" +
      "nels\030\001 \003(\0132\016.beacon.Tunnel\"t\n\022CloseTunne" +
      "lRequest\022\"\n\013agentTarget\030\001 \001(\0132\r.beacon.A" +
      "gent\022\"\n\013agentSender\030\002 \001(\0132\r.beacon.Agent" +
      "\022\026\n\016uniqueTunnelId\030\003 \001(\t\"\320\001\n\023MessageEven" +
      "tRequest\022\"\n\013agentSender\030\001 \001(\0132\r.beacon.A" +
      "gent\022$\n\teventType\030\002 \001(\0162\021.beacon.EventTy" +
      "pe\022=\n\teventData\030\003 \003(\0132*.beacon.MessageEv" +
      "entRequest.EventDataEntry\0320\n\016EventDataEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"=\n\016F" +
      "lowMessagePot\022+\n\010toDoList\030\001 \003(\0132\031.beacon" +
      ".RequestToAgentPot\"\337\001\n\021RequestToAgentPot" +
      "\022$\n\004type\030\001 \001(\0162\026.beacon.CommandTypePot\022\027" +
      "\n\017uniqueIdRequest\030\002 \001(\t\022\026\n\016requestComman" +
      "d\030\003 \001(\t\022?\n\013requestData\030\004 \003(\0132*.beacon.Re" +
      "questToAgentPot.RequestDataEntry\0322\n\020Requ" +
      "estDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"O\n\023RequestSubscription\022\016\n\006nodeId\030\001 " +
      "\001(\t\022\024\n\014samplingRate\030\002 \001(\005\022\022\n\ndataFilter\030" +
      "\003 \001(\t\"4\n\016RequestPolling\022\016\n\006nodeId\030\001 \001(\t\022" +
      "\022\n\ndataFilter\030\002 \001(\t\"-\n\017FlowMessageData\022\032" +
      "\n\004data\030\001 \003(\0132\014.beacon.Data\"\206\001\n\004Data\022\016\n\006n" +
      "odeId\030\001 \001(\t\022\037\n\004time\030\002 \001(\0132\021.beacon.Times" +
      "tamp\022\037\n\007quality\030\003 \001(\0132\016.beacon.Status\022\036\n" +
      "\004type\030\004 \001(\0162\020.beacon.DataType\022\014\n\004data\030\005 " +
      "\001(\014\"5\n\023FlowMessageDataJson\022\036\n\004data\030\001 \003(\013" +
      "2\020.beacon.DataJson\"j\n\010DataJson\022\016\n\006nodeId" +
      "\030\001 \001(\t\022\037\n\004time\030\002 \001(\0132\021.beacon.Timestamp\022" +
      "\037\n\007quality\030\003 \001(\0132\016.beacon.Status\022\014\n\004data" +
      "\030\004 \001(\t\"\216\001\n\014RequestWrite\022\016\n\006nodeId\030\001 \001(\t\022" +
      "\037\n\004time\030\002 \001(\0132\021.beacon.Timestamp\022\037\n\007qual" +
      "ity\030\003 \001(\0132\016.beacon.Status\022\036\n\004type\030\004 \001(\0162" +
      "\020.beacon.DataType\022\014\n\004data\030\005 \001(\014\"r\n\020Reque" +
      "stWriteText\022\016\n\006nodeId\030\001 \001(\t\022\037\n\004time\030\002 \001(" +
      "\0132\021.beacon.Timestamp\022\037\n\007quality\030\003 \001(\0132\016." +
      "beacon.Status\022\014\n\004data\030\004 \001(\t*;\n\013StatusVal" +
      "ue\022\010\n\004GOOD\020\000\022\007\n\003BAD\020\001\022\t\n\005FAULT\020\002\022\016\n\nWAIT" +
      "_HUMAN\020\003*g\n\013AnimaStates\022\010\n\004INIT\020\000\022\014\n\010STA" +
      "MINAL\020\001\022\016\n\nCONFIGURED\020\002\022\013\n\007RUNNING\020\003\022\n\n\006" +
      "KILLED\020\004\022\013\n\007FAULTED\020\005\022\n\n\006STASIS\020\006*|\n\013Com" +
      "mandType\022\035\n\031ELABORATE_MESSAGE_COMMAND\020\000\022" +
      "\021\n\rLIST_COMMANDS\020\001\022\024\n\020COMPLETE_COMMAND\020\002" +
      "\022\024\n\020OPEN_PROXY_SOCKS\020\003\022\017\n\013EXPOSE_PORT\020\004*" +
      "\202\001\n\013LogSeverity\022\013\n\007DEFAULT\020\000\022\t\n\005DEBUG\020d\022" +
      "\t\n\004INFO\020\310\001\022\013\n\006NOTICE\020\254\002\022\014\n\007WARNING\020\220\003\022\n\n" +
      "\005ERROR\020\364\003\022\r\n\010CRITICAL\020\330\004\022\n\n\005ALERT\020\274\005\022\016\n\t" +
      "EMERGENCY\020\240\006*9\n\nTunnelType\022\023\n\017EXPOSE_TCP" +
      "_PORT\020\000\022\026\n\022GRANT_SOCKS_ACCESS\020\001*,\n\tEvent" +
      "Type\022\017\n\013FAULT_EVENT\020\000\022\016\n\nINFO_EVENT\020\001*i\n" +
      "\016CommandTypePot\022\r\n\tSTART_POT\020\000\022\014\n\010STOP_P" +
      "OT\020\001\022\r\n\tPAUSE_POT\020\002\022\026\n\022REQUEST_STATUS_PO" +
      "T\020\003\022\023\n\017INSTANTIATE_POT\020\004*\215\001\n\010DataType\022\n\n" +
      "\006STRING\020\000\022\010\n\004CHAR\020\001\022\t\n\005BYTES\020\002\022\t\n\005INT32\020" +
      "\003\022\t\n\005INT64\020\004\022\t\n\005FLOAT\020\005\022\n\n\006DOUBLE\020\006\022\013\n\007B" +
      "OOLEAN\020\007\022\r\n\tTIMESTAMP\020\010\022\n\n\006OBJECT\020\t\022\013\n\007U" +
      "NKNOWN\020\n2\244\013\n\014RpcServiceV1\022<\n\010Register\022\027." +
      "beacon.RegisterRequest\032\025.beacon.Register" +
      "Reply\"\000\0227\n\017GetConfigTarget\022\r.beacon.Agen" +
      "t\032\023.beacon.ConfigReply\"\000\022/\n\007Polling\022\r.be" +
      "acon.Agent\032\023.beacon.FlowMessage\"\000\0226\n\014Sub" +
      "scription\022\r.beacon.Agent\032\023.beacon.FlowMe" +
      "ssage\"\0000\001\0228\n\017SendChatMessage\022\023.beacon.Ch" +
      "atMessage\032\016.beacon.Status\"\000\022A\n\020SendComma" +
      "ndReply\022\033.beacon.CommandReplyRequest\032\016.b" +
      "eacon.Status\"\000\0225\n\nSendHealth\022\025.beacon.He" +
      "althRequest\032\016.beacon.Status\"\000\022/\n\007SendLog" +
      "\022\022.beacon.LogRequest\032\016.beacon.Status\"\000\022;" +
      "\n\rSendException\022\030.beacon.ExceptionReques" +
      "t\032\016.beacon.Status\"\000\022M\n\035OpenBidirectional" +
      "SocketTunnel\022\022.beacon.StreamData\032\022.beaco" +
      "n.StreamData\"\000(\0010\001\0226\n\nListAgents\022\r.beaco" +
      "n.Empty\032\027.beacon.ListAgentsReply\"\000\022F\n\022Li" +
      "stSslAuthorities\022\r.beacon.Empty\032\037.beacon" +
      ".ListSslAuthoritiesReply\"\000\022;\n\021AddSslAuth" +
      "orities\022\024.beacon.SslAuthority\032\016.beacon.S" +
      "tatus\"\000\022<\n\022DropSslAuthorities\022\024.beacon.S" +
      "slAuthority\032\016.beacon.Status\"\000\022,\n\tKickAge" +
      "nt\022\r.beacon.Agent\032\016.beacon.Status\"\000\022T\n\020E" +
      "laborateMessage\022\037.beacon.ElaborateMessag" +
      "eRequest\032\035.beacon.ElaborateMessageReply\"" +
      "\000\022H\n\014ListCommands\022\033.beacon.ListCommandsR" +
      "equest\032\031.beacon.ListCommandsReply\"\000\022Q\n\017C" +
      "ompleteCommand\022\036.beacon.CompleteCommandR" +
      "equest\032\034.beacon.CompleteCommandReply\"\000\022_" +
      "\n\027CreateProxySocksOnAgent\022&.beacon.Creat" +
      "eProxySocksOnAgentRequest\032\032.beacon.Tunne" +
      "lCreatedReply\"\000\022O\n\017ExposeAgentPort\022\036.bea" +
      "con.ExposeAgentPortRequest\032\032.beacon.Tunn" +
      "elCreatedReply\"\000\0228\n\013ListTunnels\022\r.beacon" +
      ".Empty\032\030.beacon.ListTunnelsReply\"\000\022;\n\013Cl" +
      "oseTunnel\022\032.beacon.CloseTunnelRequest\032\016." +
      "beacon.Status\"\0002\271\001\n\014PotServiceV1\022:\n\tsend" +
      "Event\022\033.beacon.MessageEventRequest\032\016.bea" +
      "con.Status\"\000\0222\n\007Polling\022\r.beacon.Agent\032\026" +
      ".beacon.FlowMessagePot\"\000\0229\n\014Subscription" +
      "\022\r.beacon.Agent\032\026.beacon.FlowMessagePot\"" +
      "\0000\0012\336\002\n\rDataServiceV1\022<\n\007Polling\022\026.beaco" +
      "n.RequestPolling\032\027.beacon.FlowMessageDat" +
      "a\"\000\022H\n\014Subscription\022\033.beacon.RequestSubs" +
      "cription\032\027.beacon.FlowMessageData\"\0000\001\022C\n" +
      "\nPollingTxt\022\026.beacon.RequestPolling\032\033.be" +
      "acon.FlowMessageDataJson\"\000\022O\n\017Subscripti" +
      "onTxt\022\033.beacon.RequestSubscription\032\033.bea" +
      "con.FlowMessageDataJson\"\0000\001\022/\n\005write\022\024.b" +
      "eacon.RequestWrite\032\016.beacon.Status\"\000BG\n\'" +
      "org.ar4k.agent.tunnels.http.grpc.beaconB" +
      "\023BeaconMirrorServiceP\001\242\002\004AR4Kb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_beacon_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_beacon_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "RequestCsr", "DisplayKey", "Time", "JsonHealth", });
    internal_static_beacon_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_beacon_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
    internal_static_beacon_RegisterReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_beacon_RegisterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RegisterReply_descriptor,
        new java.lang.String[] { "RegisterCode", "MonitoringFrequency", "Cert", "Ca", "StatusRegistration", });
    internal_static_beacon_Status_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_beacon_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Status_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_beacon_Agent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_beacon_Agent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Agent_descriptor,
        new java.lang.String[] { "AgentUniqueName", "SecretKey", "PollingFrequency", "TimestampRegistration", });
    internal_static_beacon_ConfigReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_beacon_ConfigReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ConfigReply_descriptor,
        new java.lang.String[] { "Config", });
    internal_static_beacon_FlowMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_beacon_FlowMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_FlowMessage_descriptor,
        new java.lang.String[] { "ToDoList", });
    internal_static_beacon_RequestToAgent_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_beacon_RequestToAgent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestToAgent_descriptor,
        new java.lang.String[] { "Type", "Caller", "UniqueIdRequest", "RequestCommand", "Words", "WordIndex", "Position", });
    internal_static_beacon_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_beacon_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ChatMessage_descriptor,
        new java.lang.String[] { "AgentSender", "AgentDestination", "MessageTxt", });
    internal_static_beacon_CommandReplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_beacon_CommandReplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CommandReplyRequest_descriptor,
        new java.lang.String[] { "UniqueIdRequest", "AgentSender", "AgentDestination", "Replies", "Errors", });
    internal_static_beacon_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_beacon_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_HealthRequest_descriptor,
        new java.lang.String[] { "AgentSender", "HardwareInfo", });
    internal_static_beacon_LogRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_beacon_LogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_LogRequest_descriptor,
        new java.lang.String[] { "AgentSender", "Severity", "LogLine", });
    internal_static_beacon_ExceptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_beacon_ExceptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ExceptionRequest_descriptor,
        new java.lang.String[] { "AgentSender", "MessageException", "StackTraceException", });
    internal_static_beacon_StreamData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_beacon_StreamData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_StreamData_descriptor,
        new java.lang.String[] { "FromAgent", "ToAgent", "Data", });
    internal_static_beacon_Empty_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_beacon_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_beacon_ListAgentsReply_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_beacon_ListAgentsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ListAgentsReply_descriptor,
        new java.lang.String[] { "Result", "Agents", });
    internal_static_beacon_ListSslAuthoritiesReply_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_beacon_ListSslAuthoritiesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ListSslAuthoritiesReply_descriptor,
        new java.lang.String[] { "Result", "Authorities", });
    internal_static_beacon_SslAuthority_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_beacon_SslAuthority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_SslAuthority_descriptor,
        new java.lang.String[] { "Label", "Description", "AuthorityCa", });
    internal_static_beacon_ElaborateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_beacon_ElaborateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ElaborateMessageRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", "CommandMessage", });
    internal_static_beacon_ElaborateMessageReply_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_beacon_ElaborateMessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ElaborateMessageReply_descriptor,
        new java.lang.String[] { "Reply", "Errors", });
    internal_static_beacon_ListCommandsRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_beacon_ListCommandsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ListCommandsRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", });
    internal_static_beacon_ListCommandsReply_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_beacon_ListCommandsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ListCommandsReply_descriptor,
        new java.lang.String[] { "Commands", });
    internal_static_beacon_Command_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_beacon_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Command_descriptor,
        new java.lang.String[] { "AgentSender", "Command", });
    internal_static_beacon_CompleteCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_beacon_CompleteCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CompleteCommandRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", "Words", "WordIndex", "Position", });
    internal_static_beacon_CompleteCommandReply_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_beacon_CompleteCommandReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CompleteCommandReply_descriptor,
        new java.lang.String[] { "Replies", "Errors", });
    internal_static_beacon_CreateProxySocksOnAgentRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_beacon_CreateProxySocksOnAgentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CreateProxySocksOnAgentRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", "Parameters", });
    internal_static_beacon_CreateProxySocksOnAgentRequest_ParametersEntry_descriptor =
      internal_static_beacon_CreateProxySocksOnAgentRequest_descriptor.getNestedTypes().get(0);
    internal_static_beacon_CreateProxySocksOnAgentRequest_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CreateProxySocksOnAgentRequest_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_beacon_TunnelCreatedReply_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_beacon_TunnelCreatedReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_TunnelCreatedReply_descriptor,
        new java.lang.String[] { "UniqueTunnelId", "Status", "Tunnel", });
    internal_static_beacon_ExposeAgentPortRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_beacon_ExposeAgentPortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ExposeAgentPortRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", "Parameters", });
    internal_static_beacon_ExposeAgentPortRequest_ParametersEntry_descriptor =
      internal_static_beacon_ExposeAgentPortRequest_descriptor.getNestedTypes().get(0);
    internal_static_beacon_ExposeAgentPortRequest_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ExposeAgentPortRequest_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_beacon_Tunnel_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_beacon_Tunnel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Tunnel_descriptor,
        new java.lang.String[] { "UniqueTunnelId", "AgentFrom", "AgentTo", "Type", "Parameters", });
    internal_static_beacon_Tunnel_ParametersEntry_descriptor =
      internal_static_beacon_Tunnel_descriptor.getNestedTypes().get(0);
    internal_static_beacon_Tunnel_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Tunnel_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_beacon_ListTunnelsReply_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_beacon_ListTunnelsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_ListTunnelsReply_descriptor,
        new java.lang.String[] { "Tunnels", });
    internal_static_beacon_CloseTunnelRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_beacon_CloseTunnelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_CloseTunnelRequest_descriptor,
        new java.lang.String[] { "AgentTarget", "AgentSender", "UniqueTunnelId", });
    internal_static_beacon_MessageEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_beacon_MessageEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_MessageEventRequest_descriptor,
        new java.lang.String[] { "AgentSender", "EventType", "EventData", });
    internal_static_beacon_MessageEventRequest_EventDataEntry_descriptor =
      internal_static_beacon_MessageEventRequest_descriptor.getNestedTypes().get(0);
    internal_static_beacon_MessageEventRequest_EventDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_MessageEventRequest_EventDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_beacon_FlowMessagePot_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_beacon_FlowMessagePot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_FlowMessagePot_descriptor,
        new java.lang.String[] { "ToDoList", });
    internal_static_beacon_RequestToAgentPot_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_beacon_RequestToAgentPot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestToAgentPot_descriptor,
        new java.lang.String[] { "Type", "UniqueIdRequest", "RequestCommand", "RequestData", });
    internal_static_beacon_RequestToAgentPot_RequestDataEntry_descriptor =
      internal_static_beacon_RequestToAgentPot_descriptor.getNestedTypes().get(0);
    internal_static_beacon_RequestToAgentPot_RequestDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestToAgentPot_RequestDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_beacon_RequestSubscription_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_beacon_RequestSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestSubscription_descriptor,
        new java.lang.String[] { "NodeId", "SamplingRate", "DataFilter", });
    internal_static_beacon_RequestPolling_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_beacon_RequestPolling_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestPolling_descriptor,
        new java.lang.String[] { "NodeId", "DataFilter", });
    internal_static_beacon_FlowMessageData_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_beacon_FlowMessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_FlowMessageData_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_beacon_Data_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_beacon_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_Data_descriptor,
        new java.lang.String[] { "NodeId", "Time", "Quality", "Type", "Data", });
    internal_static_beacon_FlowMessageDataJson_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_beacon_FlowMessageDataJson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_FlowMessageDataJson_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_beacon_DataJson_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_beacon_DataJson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_DataJson_descriptor,
        new java.lang.String[] { "NodeId", "Time", "Quality", "Data", });
    internal_static_beacon_RequestWrite_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_beacon_RequestWrite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestWrite_descriptor,
        new java.lang.String[] { "NodeId", "Time", "Quality", "Type", "Data", });
    internal_static_beacon_RequestWriteText_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_beacon_RequestWriteText_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beacon_RequestWriteText_descriptor,
        new java.lang.String[] { "NodeId", "Time", "Quality", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
