// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface FlowMessagePotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.FlowMessagePot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .beacon.RequestToAgentPot toDoList = 1;</code>
   */
  java.util.List<org.ar4k.agent.tunnels.http.grpc.beacon.RequestToAgentPot> 
      getToDoListList();
  /**
   * <code>repeated .beacon.RequestToAgentPot toDoList = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.RequestToAgentPot getToDoList(int index);
  /**
   * <code>repeated .beacon.RequestToAgentPot toDoList = 1;</code>
   */
  int getToDoListCount();
  /**
   * <code>repeated .beacon.RequestToAgentPot toDoList = 1;</code>
   */
  java.util.List<? extends org.ar4k.agent.tunnels.http.grpc.beacon.RequestToAgentPotOrBuilder> 
      getToDoListOrBuilderList();
  /**
   * <code>repeated .beacon.RequestToAgentPot toDoList = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.RequestToAgentPotOrBuilder getToDoListOrBuilder(
      int index);
}
