// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface ListStringReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.ListStringReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  boolean hasAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.Agent getAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.AgentOrBuilder getAgentSenderOrBuilder();

  /**
   * <code>repeated string listDatas = 2;</code>
   */
  java.util.List<java.lang.String>
      getListDatasList();
  /**
   * <code>repeated string listDatas = 2;</code>
   */
  int getListDatasCount();
  /**
   * <code>repeated string listDatas = 2;</code>
   */
  java.lang.String getListDatas(int index);
  /**
   * <code>repeated string listDatas = 2;</code>
   */
  com.google.protobuf.ByteString
      getListDatasBytes(int index);

  /**
   * <code>int32 linesNumber = 3;</code>
   */
  int getLinesNumber();
}
