// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface LogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.LogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  boolean hasAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.Agent getAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.AgentOrBuilder getAgentSenderOrBuilder();

  /**
   * <code>.beacon.LogSeverity severity = 2;</code>
   */
  int getSeverityValue();
  /**
   * <code>.beacon.LogSeverity severity = 2;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.LogSeverity getSeverity();

  /**
   * <code>string logLine = 3;</code>
   */
  java.lang.String getLogLine();
  /**
   * <code>string logLine = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogLineBytes();
}
