// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http.grpc.beacon;

public interface RegisterReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.RegisterReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beacon.Status result = 1;</code>
   */
  int getResultValue();
  /**
   * <code>.beacon.Status result = 1;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.Status getResult();

  /**
   * <code>string registerCode = 2;</code>
   */
  java.lang.String getRegisterCode();
  /**
   * <code>string registerCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getRegisterCodeBytes();

  /**
   * <code>int32 monitoringFrequency = 3;</code>
   */
  int getMonitoringFrequency();

  /**
   * <code>.beacon.AnimaStates targetState = 4;</code>
   */
  int getTargetStateValue();
  /**
   * <code>.beacon.AnimaStates targetState = 4;</code>
   */
  org.ar4k.agent.tunnels.http.grpc.beacon.AnimaStates getTargetState();
}
