// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ar4k_beacon.proto

package org.ar4k.agent.tunnels.http2.grpc.beacon;

public interface CommandReplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.CommandReplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uniqueIdRequest = 1;</code>
   */
  java.lang.String getUniqueIdRequest();
  /**
   * <code>string uniqueIdRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getUniqueIdRequestBytes();

  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   */
  boolean hasAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.Agent getAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.AgentOrBuilder getAgentSenderOrBuilder();

  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   */
  boolean hasAgentDestination();
  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.Agent getAgentDestination();
  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.AgentOrBuilder getAgentDestinationOrBuilder();

  /**
   * <code>repeated string replies = 4;</code>
   */
  java.util.List<java.lang.String>
      getRepliesList();
  /**
   * <code>repeated string replies = 4;</code>
   */
  int getRepliesCount();
  /**
   * <code>repeated string replies = 4;</code>
   */
  java.lang.String getReplies(int index);
  /**
   * <code>repeated string replies = 4;</code>
   */
  com.google.protobuf.ByteString
      getRepliesBytes(int index);

  /**
   * <code>repeated string errors = 5;</code>
   */
  java.util.List<java.lang.String>
      getErrorsList();
  /**
   * <code>repeated string errors = 5;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated string errors = 5;</code>
   */
  java.lang.String getErrors(int index);
  /**
   * <code>repeated string errors = 5;</code>
   */
  com.google.protobuf.ByteString
      getErrorsBytes(int index);

  /**
   * <code>.beacon.ResponseNetworkChannel tunnelReply = 6;</code>
   */
  boolean hasTunnelReply();
  /**
   * <code>.beacon.ResponseNetworkChannel tunnelReply = 6;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.ResponseNetworkChannel getTunnelReply();
  /**
   * <code>.beacon.ResponseNetworkChannel tunnelReply = 6;</code>
   */
  org.ar4k.agent.tunnels.http2.grpc.beacon.ResponseNetworkChannelOrBuilder getTunnelReplyOrBuilder();

  /**
   * <code>string base64Config = 7;</code>
   */
  java.lang.String getBase64Config();
  /**
   * <code>string base64Config = 7;</code>
   */
  com.google.protobuf.ByteString
      getBase64ConfigBytes();

  /**
   * <code>int64 restartAt = 8;</code>
   */
  long getRestartAt();
}
