// Generated by delombok at Sun Apr 18 22:20:18 CEST 2021
/*
 * Copyright (c) 2016-present, Takayuki Maruyama
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ar4k.agent.mattermost.model.config;

/**
 * Compliance settings.
 * 
 * @author Takayuki Maruyama
 */
public class ComplianceSettings {
  private boolean enable;
  private String directory;
  private boolean enableDaily;

  @java.lang.SuppressWarnings("all")
  public ComplianceSettings() {
  }

  @java.lang.SuppressWarnings("all")
  public boolean isEnable() {
    return this.enable;
  }

  @java.lang.SuppressWarnings("all")
  public String getDirectory() {
    return this.directory;
  }

  @java.lang.SuppressWarnings("all")
  public boolean isEnableDaily() {
    return this.enableDaily;
  }

  @java.lang.SuppressWarnings("all")
  public void setEnable(final boolean enable) {
    this.enable = enable;
  }

  @java.lang.SuppressWarnings("all")
  public void setDirectory(final String directory) {
    this.directory = directory;
  }

  @java.lang.SuppressWarnings("all")
  public void setEnableDaily(final boolean enableDaily) {
    this.enableDaily = enableDaily;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof ComplianceSettings)) return false;
    final ComplianceSettings other = (ComplianceSettings) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (this.isEnable() != other.isEnable()) return false;
    if (this.isEnableDaily() != other.isEnableDaily()) return false;
    final java.lang.Object this$directory = this.getDirectory();
    final java.lang.Object other$directory = other.getDirectory();
    if (this$directory == null ? other$directory != null : !this$directory.equals(other$directory)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof ComplianceSettings;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + (this.isEnable() ? 79 : 97);
    result = result * PRIME + (this.isEnableDaily() ? 79 : 97);
    final java.lang.Object $directory = this.getDirectory();
    result = result * PRIME + ($directory == null ? 43 : $directory.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "ComplianceSettings(enable=" + this.isEnable() + ", directory=" + this.getDirectory() + ", enableDaily=" + this.isEnableDaily() + ")";
  }
}
