// Generated by delombok at Sun Apr 18 22:20:18 CEST 2021
/*
 * Copyright (c) 2016-present, Takayuki Maruyama
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ar4k.agent.mattermost.model.config;

/**
 * SSO settings.
 * 
 * @author Takayuki Maruyama
 */
public class SsoSettings {
  private boolean enable;
  private String secret;
  private String id;
  private String scope;
  private String authEndpoint;
  private String tokenEndpoint;
  private String userApiEndpoint;

  @java.lang.SuppressWarnings("all")
  public SsoSettings() {
  }

  @java.lang.SuppressWarnings("all")
  public boolean isEnable() {
    return this.enable;
  }

  @java.lang.SuppressWarnings("all")
  public String getSecret() {
    return this.secret;
  }

  @java.lang.SuppressWarnings("all")
  public String getId() {
    return this.id;
  }

  @java.lang.SuppressWarnings("all")
  public String getScope() {
    return this.scope;
  }

  @java.lang.SuppressWarnings("all")
  public String getAuthEndpoint() {
    return this.authEndpoint;
  }

  @java.lang.SuppressWarnings("all")
  public String getTokenEndpoint() {
    return this.tokenEndpoint;
  }

  @java.lang.SuppressWarnings("all")
  public String getUserApiEndpoint() {
    return this.userApiEndpoint;
  }

  @java.lang.SuppressWarnings("all")
  public void setEnable(final boolean enable) {
    this.enable = enable;
  }

  @java.lang.SuppressWarnings("all")
  public void setSecret(final String secret) {
    this.secret = secret;
  }

  @java.lang.SuppressWarnings("all")
  public void setId(final String id) {
    this.id = id;
  }

  @java.lang.SuppressWarnings("all")
  public void setScope(final String scope) {
    this.scope = scope;
  }

  @java.lang.SuppressWarnings("all")
  public void setAuthEndpoint(final String authEndpoint) {
    this.authEndpoint = authEndpoint;
  }

  @java.lang.SuppressWarnings("all")
  public void setTokenEndpoint(final String tokenEndpoint) {
    this.tokenEndpoint = tokenEndpoint;
  }

  @java.lang.SuppressWarnings("all")
  public void setUserApiEndpoint(final String userApiEndpoint) {
    this.userApiEndpoint = userApiEndpoint;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof SsoSettings)) return false;
    final SsoSettings other = (SsoSettings) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (this.isEnable() != other.isEnable()) return false;
    final java.lang.Object this$secret = this.getSecret();
    final java.lang.Object other$secret = other.getSecret();
    if (this$secret == null ? other$secret != null : !this$secret.equals(other$secret)) return false;
    final java.lang.Object this$id = this.getId();
    final java.lang.Object other$id = other.getId();
    if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
    final java.lang.Object this$scope = this.getScope();
    final java.lang.Object other$scope = other.getScope();
    if (this$scope == null ? other$scope != null : !this$scope.equals(other$scope)) return false;
    final java.lang.Object this$authEndpoint = this.getAuthEndpoint();
    final java.lang.Object other$authEndpoint = other.getAuthEndpoint();
    if (this$authEndpoint == null ? other$authEndpoint != null : !this$authEndpoint.equals(other$authEndpoint)) return false;
    final java.lang.Object this$tokenEndpoint = this.getTokenEndpoint();
    final java.lang.Object other$tokenEndpoint = other.getTokenEndpoint();
    if (this$tokenEndpoint == null ? other$tokenEndpoint != null : !this$tokenEndpoint.equals(other$tokenEndpoint)) return false;
    final java.lang.Object this$userApiEndpoint = this.getUserApiEndpoint();
    final java.lang.Object other$userApiEndpoint = other.getUserApiEndpoint();
    if (this$userApiEndpoint == null ? other$userApiEndpoint != null : !this$userApiEndpoint.equals(other$userApiEndpoint)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof SsoSettings;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + (this.isEnable() ? 79 : 97);
    final java.lang.Object $secret = this.getSecret();
    result = result * PRIME + ($secret == null ? 43 : $secret.hashCode());
    final java.lang.Object $id = this.getId();
    result = result * PRIME + ($id == null ? 43 : $id.hashCode());
    final java.lang.Object $scope = this.getScope();
    result = result * PRIME + ($scope == null ? 43 : $scope.hashCode());
    final java.lang.Object $authEndpoint = this.getAuthEndpoint();
    result = result * PRIME + ($authEndpoint == null ? 43 : $authEndpoint.hashCode());
    final java.lang.Object $tokenEndpoint = this.getTokenEndpoint();
    result = result * PRIME + ($tokenEndpoint == null ? 43 : $tokenEndpoint.hashCode());
    final java.lang.Object $userApiEndpoint = this.getUserApiEndpoint();
    result = result * PRIME + ($userApiEndpoint == null ? 43 : $userApiEndpoint.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "SsoSettings(enable=" + this.isEnable() + ", secret=" + this.getSecret() + ", id=" + this.getId() + ", scope=" + this.getScope() + ", authEndpoint=" + this.getAuthEndpoint() + ", tokenEndpoint=" + this.getTokenEndpoint() + ", userApiEndpoint=" + this.getUserApiEndpoint() + ")";
  }
}
