//created on: 9-apr-2020
package drools

import org.ar4k.agent.cortex.drools.data.DataFactWrapper
import org.ar4k.agent.cortex.drools.internals.GlobalLoggerUtils
import org.ar4k.agent.cortex.drools.data.GlobalDataInterface

global GlobalLoggerUtils logger
global GlobalDataInterface utils

dialect "mvel"

rule "print messager in log"
    when
        $message: DataFactWrapper();
    then
        logger.writeInfoLog($message.getData());
end

rule "simple numerical data x 2"
    when
        $number: DataFactWrapper(getDataAsLong() != null)
    then
    	logger.writeInfoLog("numerical data found");
        logger.writeInfoLog(utils.getString($number.getDataAsLong() * 2));
end
