name: Build docs and publish on web.rossonet.net

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print env
      run: echo $GITHUB_ACTOR
    - name: Clone sub repos
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        git submodule init
        git submodule update
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip     # install pip
        python3 -m pip install mkdocs            # install mkdocs 
        python3 -m pip install mkdocs-material   # install material theme
    - name: Build docs
      run: ./scripts/genera-documentazione.sh
    - name: Publish docs
      env:
        SSH_TOKEN: ${{ secrets.WEB_GITHUB_AR4K }}
      run: ./scripts/publish-docs.sh
