name: Build QA jar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew ar4kBootJarQa
    - uses: actions/upload-artifact@v1
      with:
        name: uploadQa
        path: ar4k-agent-qa/build/libs
        expires: 86400

