// Generated by delombok at Sun Apr 18 22:20:18 CEST 2021
/*
 * Copyright (c) 2016-present, Takayuki Maruyama
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ar4k.agent.mattermost.model.license;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Features.
 *
 * @author Takayuki Maruyama
 */
public class Features {
	@JsonProperty("users")
	private int users;
	@JsonProperty("ldap")
	private boolean ldap;
	@JsonProperty("mfa")
	private boolean mfa;
	@JsonProperty("google_oauth")
	private boolean googleOAuth;
	@JsonProperty("office365_oauth")
	private boolean office365OAuth;
	@JsonProperty("compliance")
	private boolean compliance;
	@JsonProperty("cluster")
	private boolean cluster;
	@JsonProperty("metrics")
	private boolean metrics;
	@JsonProperty("custom_brand")
	private boolean customBrand;
	@JsonProperty("mhpns")
	private boolean mhpns;
	@JsonProperty("saml")
	private boolean saml;
	@JsonProperty("password_requirements")
	private boolean passwordRequirements;
	// after we enabled more features for webrtc we'll need to control them with
	// this
	@JsonProperty("future_features")
	private boolean futureFeatures;

	@java.lang.SuppressWarnings("all")
	public Features() {
	}

	@java.lang.SuppressWarnings("all")
	public int getUsers() {
		return this.users;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isLdap() {
		return this.ldap;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isMfa() {
		return this.mfa;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isGoogleOAuth() {
		return this.googleOAuth;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isOffice365OAuth() {
		return this.office365OAuth;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isCompliance() {
		return this.compliance;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isCluster() {
		return this.cluster;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isMetrics() {
		return this.metrics;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isCustomBrand() {
		return this.customBrand;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isMhpns() {
		return this.mhpns;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isSaml() {
		return this.saml;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isPasswordRequirements() {
		return this.passwordRequirements;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFutureFeatures() {
		return this.futureFeatures;
	}

	@JsonProperty("users")
	@java.lang.SuppressWarnings("all")
	public void setUsers(final int users) {
		this.users = users;
	}

	@JsonProperty("ldap")
	@java.lang.SuppressWarnings("all")
	public void setLdap(final boolean ldap) {
		this.ldap = ldap;
	}

	@JsonProperty("mfa")
	@java.lang.SuppressWarnings("all")
	public void setMfa(final boolean mfa) {
		this.mfa = mfa;
	}

	@JsonProperty("google_oauth")
	@java.lang.SuppressWarnings("all")
	public void setGoogleOAuth(final boolean googleOAuth) {
		this.googleOAuth = googleOAuth;
	}

	@JsonProperty("office365_oauth")
	@java.lang.SuppressWarnings("all")
	public void setOffice365OAuth(final boolean office365OAuth) {
		this.office365OAuth = office365OAuth;
	}

	@JsonProperty("compliance")
	@java.lang.SuppressWarnings("all")
	public void setCompliance(final boolean compliance) {
		this.compliance = compliance;
	}

	@JsonProperty("cluster")
	@java.lang.SuppressWarnings("all")
	public void setCluster(final boolean cluster) {
		this.cluster = cluster;
	}

	@JsonProperty("metrics")
	@java.lang.SuppressWarnings("all")
	public void setMetrics(final boolean metrics) {
		this.metrics = metrics;
	}

	@JsonProperty("custom_brand")
	@java.lang.SuppressWarnings("all")
	public void setCustomBrand(final boolean customBrand) {
		this.customBrand = customBrand;
	}

	@JsonProperty("mhpns")
	@java.lang.SuppressWarnings("all")
	public void setMhpns(final boolean mhpns) {
		this.mhpns = mhpns;
	}

	@JsonProperty("saml")
	@java.lang.SuppressWarnings("all")
	public void setSaml(final boolean saml) {
		this.saml = saml;
	}

	@JsonProperty("password_requirements")
	@java.lang.SuppressWarnings("all")
	public void setPasswordRequirements(final boolean passwordRequirements) {
		this.passwordRequirements = passwordRequirements;
	}

	@JsonProperty("future_features")
	@java.lang.SuppressWarnings("all")
	public void setFutureFeatures(final boolean futureFeatures) {
		this.futureFeatures = futureFeatures;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Features)) return false;
		final Features other = (Features) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.getUsers() != other.getUsers()) return false;
		if (this.isLdap() != other.isLdap()) return false;
		if (this.isMfa() != other.isMfa()) return false;
		if (this.isGoogleOAuth() != other.isGoogleOAuth()) return false;
		if (this.isOffice365OAuth() != other.isOffice365OAuth()) return false;
		if (this.isCompliance() != other.isCompliance()) return false;
		if (this.isCluster() != other.isCluster()) return false;
		if (this.isMetrics() != other.isMetrics()) return false;
		if (this.isCustomBrand() != other.isCustomBrand()) return false;
		if (this.isMhpns() != other.isMhpns()) return false;
		if (this.isSaml() != other.isSaml()) return false;
		if (this.isPasswordRequirements() != other.isPasswordRequirements()) return false;
		if (this.isFutureFeatures() != other.isFutureFeatures()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Features;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getUsers();
		result = result * PRIME + (this.isLdap() ? 79 : 97);
		result = result * PRIME + (this.isMfa() ? 79 : 97);
		result = result * PRIME + (this.isGoogleOAuth() ? 79 : 97);
		result = result * PRIME + (this.isOffice365OAuth() ? 79 : 97);
		result = result * PRIME + (this.isCompliance() ? 79 : 97);
		result = result * PRIME + (this.isCluster() ? 79 : 97);
		result = result * PRIME + (this.isMetrics() ? 79 : 97);
		result = result * PRIME + (this.isCustomBrand() ? 79 : 97);
		result = result * PRIME + (this.isMhpns() ? 79 : 97);
		result = result * PRIME + (this.isSaml() ? 79 : 97);
		result = result * PRIME + (this.isPasswordRequirements() ? 79 : 97);
		result = result * PRIME + (this.isFutureFeatures() ? 79 : 97);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Features(users=" + this.getUsers() + ", ldap=" + this.isLdap() + ", mfa=" + this.isMfa() + ", googleOAuth=" + this.isGoogleOAuth() + ", office365OAuth=" + this.isOffice365OAuth() + ", compliance=" + this.isCompliance() + ", cluster=" + this.isCluster() + ", metrics=" + this.isMetrics() + ", customBrand=" + this.isCustomBrand() + ", mhpns=" + this.isMhpns() + ", saml=" + this.isSaml() + ", passwordRequirements=" + this.isPasswordRequirements() + ", futureFeatures=" + this.isFutureFeatures() + ")";
	}
}
